version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: frontend-standalone
    ports:
      - "80:80"
    environment:
      # URL por defecto para pruebas locales independientes
      - VITE_API_BASE_URL=http://localhost:8091