name: CI/CD Pipeline - Frontend

on:
  push:
    branches:
      - deploy # El pipeline solo se activará cuando hagas push a esta rama

jobs:
  build-push-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: 1. Descargar el código
      uses: actions/checkout@v3

    - name: 2. Configurar Credenciales de AWS
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
        aws-region: us-east-1

    - name: 3. Iniciar sesión en Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: 4. Construir y Subir Imagen Docker a ECR
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: innovatech-frontend
        IMAGE_TAG: latest
      run: |
        # Como el Dockerfile está en la raíz, construimos directamente
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
        
        # Sube la nueva imagen a AWS ECR
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

    - name: 5. Conectar a Kubernetes (EKS)
      run: |
        aws eks update-kubeconfig --region us-east-1 --name innovatech-eks

    - name: 6. Desplegar Infraestructura en EKS
      run: |
        # Aplica los archivos de Kubernetes (asegúrate de que la carpeta k8s esté en este repo también)
        kubectl apply -f k8s/innovatech-secret.yaml
        kubectl apply -f k8s/innovatech-deploy.yaml
        kubectl apply -f k8s/innovatech-hpa.yaml
        
        # OJO AQUÍ: Reiniciamos específicamente el frontend para que tome los cambios de inmediato
        kubectl rollout restart deployment frontend-deployment